name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get GCC
      run: sudo apt install gcc-arm-none-eabi -y
    - name: make RPI0=1
      run: mkdir ./RPI_BASE/build && cd RPI_BASE && make qemu-build RPI0=1 && cd ..
